// in px (pixels)
const GRID_WIDTH = 1500;
const GRID_HEIGHT = 600;
const CELL_DIMENSION = 30;

const NUMBER_OF_ROWS = GRID_HEIGHT / CELL_DIMENSION;
const NUMBER_OF_COLUMNS = GRID_WIDTH / CELL_DIMENSION;

export {
  GRID_HEIGHT,
  GRID_WIDTH,
  CELL_DIMENSION,
  NUMBER_OF_COLUMNS,
  NUMBER_OF_ROWS,
};
